### ISSUE TITLE
nim [object | web ] get command has counter-intuitive default behavior

### ISSUE THREAD

**Issue by sciabarracom** [nimbella/nimbella-cli#41] opened 2021-01-03 16:16 UTC
Version:
```
nim --version
nimbella-cli/1.10.2 darwin-x64 node-v14.4.0
```

Problem:

```
$ nim object get dino.jpg
getting dino.jpg... done


/Users/msciab/.local/share/nimbella-cli/client/1.10.2/lib/commands/object/get.js:1
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const command_1=require("@oclif/command"),nimbella_deployer_1=require("nimbella-deployer"),nimbella_deployer_2=require("nimbella-deployer"),clients_1=require("../../storage/clients"),fs_1=require("fs"),path_1=require("path"),ui_1=require("../../ui"),util_1=require("../../storage/util");class ObjectGet extends nimbella_deployer_1.NimBaseCommand{async runCommand(e,t,o,a,n){const{client:i}=await clients_1.getObjectStorageClient(o,a,nimbella_deployer_2.authPersister);i||n.handleError(`Couldn't get to the object store, ensure it's enabled for the ${o.namespace||"current"} namespace`),await this.downloadFile(o.objectName,o.destination,i,n,a.saveAs,a.save).catch(e=>n.handleError("",e))}async downloadFile(e,t,o,a,n,i=!1){fs_1.existsSync(t)||a.handleError(t+" doesn't exist");const s=await ui_1.spinner();if(s.start("getting "+e,"downloading",{stdout:!0}),i||n){const a=path_1.basename(e);await o.file(e).download({destination:path_1.join(t,n||a)}).then(e=>s.stop("done"))}else o.file(e).download((function(t,o){t?(s.stop("couldn't print content"),util_1.errorHandler(t,a,e)):(s.stop(),a.log("\n"),a.log(String.fromCharCode.apply(null,o)))}))}}exports.default=ObjectGet,ObjectGet.description="Gets Object from the Object Store",ObjectGet.flags=Object.assign({apihost:command_1.flags.string({description:"API host of the namespace to get object from"}),save:command_1.flags.boolean({char:"s",description:"Saves object on file system"}),saveAs:command_1.flags.string({description:"Saves object on file system with the given name"})},nimbella_deployer_1.NimBaseCommand.flags),ObjectGet.args=[{name:"objectName",description:"The object to get",required:!0},{name:"destination",description:"The location to write object at",required:!0,default:"./"},{name:"namespace",description:"The namespace to get object from (current namespace if omitted)",required:!1}];


RangeError: Maximum call stack size exceeded
    at /Users/msciab/.local/share/nimbella-cli/client/1.10.2/lib/commands/object/get.js:1:1194
    at /Users/msciab/.local/share/nimbella-cli/client/1.10.2/node_modules/onetime/index.js:19:28
    at ConcatStream.<anonymous> (/Users/msciab/.local/share/nimbella-cli/client/1.10.2/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:327:22)
    at finishMaybe (/Users/msciab/.local/share/nimbella-cli/client/1.10.2/node_modules/readable-stream/lib/_stream_writable.js:624:14)
    at endWritable (/Users/msciab/.local/share/nimbella-cli/client/1.10.2/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at ConcatStream.Writable.end (/Users/msciab/.local/share/nimbella-cli/client/1.10.2/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at PassThrough.onend (_stream_readable.js:677:10)
    at Object.onceWrapper (events.js:421:28)
    at PassThrough.emit (events.js:315:20)
```

**Comment by joshuaauerbachwatson** [comment] 2021-01-03 17:38
This happens because the default behavior of `nim object get` (and `nim web get`) is to print to the console rather than saving the file.   The logic it is using, also, is suitable only for small files (larger ones can readily blow the stack).

An immediate circumvention is to add the `--save` flag.  This will cause the file to be saved to a local file.

Others have tripped over this.   Since the code is behaving as designed, I'm going to retitle the issue.  I think the issue here is that the choice of console printing as the default behavior violates the least astonishment principle.   The default ought to be to save the file, and there should be a separate verb for printing files to the console.

I recall the discussion with Chandan about this and I think at the time I was urging him to make the new commands for `web` and `object` similar in behavior to other `nim` commands derived from aio (which was in turn based on wsk).   So, e.g., the `action get` command will print unless you specify `--save`.   But, I think I failed to appreciate that what `action get` prints is metadata and what it saves is code, so this is not a good analogy.

**Comment by joshuaauerbachwatson** [comment] 2021-01-22 14:37
@bhageena we should discuss the new syntax here and also whether or not to classify this as a breaking change (it is, technically, but I'm not sure how tight to be about that).   I'll await a proposal on the syntax.

**Comment by rabbah** [comment] 2021-01-22 14:41
I favor web/object get on a file to imply save, with a flag to print to console if the contents are printable. A save-as flag should also be added to rename the local file or specify a directory other than the working dir.

**Comment by bhageena** [comment] 2021-01-25 06:55
`--save` is implied by default now.

**nim web get 404.html** 
will download the 404.html in the current dir.

**nim web get 404.html [--print|-p]** 
will print the 404.html content on the terminal (even though the content is not readable e.g. png files, will show `couldn\'t print content` when content is not printable)

**nim web get 404.html --saveAs 405.html** 
will download the 404.html as 405.html in the current dir

The same goes with **object get**

**Comment by rabbah** [comment] 2021-01-25 07:30
Please check action get —help. I think the save as flag used for both commands should be the same. 
SaveAs or save-as

**Comment by bhageena** [comment] 2021-01-25 08:22
> Please check action get —help. I think the save as flag used for both commands should be the same.

In the case of web, it says
**--saveAs=saveAs**        Saves content on file system with the given name

for objects, it's 
**--saveAs=saveAs**        Saves object on file system with the given name

has description text to be identical i.e. `Saves file on disk with the given name`

or `--saveAs` needs to changed as `--save-as`  for both commands

**Comment by joshuaauerbachwatson** [comment] 2021-01-25 15:34
> A save flag does make sense (avoiding the breaking change) and does mirror action get --save.

Technically, supporting a `--save` flag that does nothing does not avoid a "breaking change" in the sense that a `get` operation without the `--save` would save to the file system whereas before it would print.   My feeling is we can use some judgment here, though.

- tolerating the presence of `--save` makes the change "less breaking"
- the old default print behavior caused lots of problems ... in fact, this issue was originally opened as a bug, so I doubt many users would feel the change was "breaking"
- consequently, I am comfortable with _not_ classifying this as a breaking change

> or `--saveAs` needs to changed as `--save-as` for both commands

I think that's what Rodric was asking.   However, since `--saveAs` is pre-existing, it _would_ be a breaking change to simply change it to `--save-as` so I think we need to support both with equivalent behavior.

**Comment by bhageena** [comment] 2021-01-25 17:06
sure, I'll update the PR to include `--save-as` along with --saveAs

**Comment by joshuaauerbachwatson** [comment] 2021-01-25 17:08
In addition, I think the help text for --save should say that it is the default.

**Comment by joshuaauerbachwatson** [comment] 2021-01-25 18:42
PR #55 is merged so this is now awaiting a stable version.  Adding myself as an assignee so I remember.

**Comment by joshuaauerbachwatson** [comment] 2021-01-26 20:15
In stable version 1.12

**Closed by joshuaauerbachwatson** 2021-01-26 20:15 UTC
